/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Person_CONSTANTS_H
#define Person_CONSTANTS_H

#include "Person_types.h"

namespace IDV {

class PersonConstants {
 public:
  PersonConstants();

};

extern const PersonConstants g_Person_constants;

} // namespace

#endif
