// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "PersonService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::IDV;

class PersonServiceHandler : virtual public PersonServiceIf {
 public:
  PersonServiceHandler() {
    // Your initialization goes here
  }

  void getPersonById(Person& _return, const int32_t id) {
    // Your implementation goes here
    printf("getPersonById\n");
  }

  bool deletePersonById(const int32_t id) {
    // Your implementation goes here
    printf("deletePersonById\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<PersonServiceHandler> handler(new PersonServiceHandler());
  shared_ptr<TProcessor> processor(new PersonServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

