/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Person_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace IDV {


Person::~Person() throw() {
}


void Person::__set_id(const int32_t val) {
  this->id = val;
}

void Person::__set_name(const std::string& val) {
  this->name = val;
}

void Person::__set_age(const int32_t val) {
  this->age = val;
}

void Person::__set_married(const bool val) {
  this->married = val;
}

const char* Person::ascii_fingerprint = "BE8D9CA2BE3F970D4DB8E5BF41DCA869";
const uint8_t Person::binary_fingerprint[16] = {0xBE,0x8D,0x9C,0xA2,0xBE,0x3F,0x97,0x0D,0x4D,0xB8,0xE5,0xBF,0x41,0xDC,0xA8,0x69};

uint32_t Person::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->id);
          this->__isset.id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->age);
          this->__isset.age = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->married);
          this->__isset.married = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Person::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("Person");

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("age", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(this->age);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("married", ::apache::thrift::protocol::T_BOOL, 4);
  xfer += oprot->writeBool(this->married);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(Person &a, Person &b) {
  using ::std::swap;
  swap(a.id, b.id);
  swap(a.name, b.name);
  swap(a.age, b.age);
  swap(a.married, b.married);
  swap(a.__isset, b.__isset);
}

Person::Person(const Person& other0) {
  id = other0.id;
  name = other0.name;
  age = other0.age;
  married = other0.married;
  __isset = other0.__isset;
}
Person& Person::operator=(const Person& other1) {
  id = other1.id;
  name = other1.name;
  age = other1.age;
  married = other1.married;
  __isset = other1.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const Person& obj) {
  using apache::thrift::to_string;
  out << "Person(";
  out << "id=" << to_string(obj.id);
  out << ", " << "name=" << to_string(obj.name);
  out << ", " << "age=" << to_string(obj.age);
  out << ", " << "married=" << to_string(obj.married);
  out << ")";
  return out;
}

} // namespace
