/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Person_constants.h"

namespace IDV {

const PersonConstants g_Person_constants;

PersonConstants::PersonConstants() {
}

} // namespace

