/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Person_TYPES_H
#define Person_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace IDV {

class Person;

typedef struct _Person__isset {
  _Person__isset() : id(false), name(false), age(false), married(false) {}
  bool id :1;
  bool name :1;
  bool age :1;
  bool married :1;
} _Person__isset;

class Person {
 public:

  static const char* ascii_fingerprint; // = "BE8D9CA2BE3F970D4DB8E5BF41DCA869";
  static const uint8_t binary_fingerprint[16]; // = {0xBE,0x8D,0x9C,0xA2,0xBE,0x3F,0x97,0x0D,0x4D,0xB8,0xE5,0xBF,0x41,0xDC,0xA8,0x69};

  Person(const Person&);
  Person& operator=(const Person&);
  Person() : id(0), name(), age(0), married(0) {
  }

  virtual ~Person() throw();
  int32_t id;
  std::string name;
  int32_t age;
  bool married;

  _Person__isset __isset;

  void __set_id(const int32_t val);

  void __set_name(const std::string& val);

  void __set_age(const int32_t val);

  void __set_married(const bool val);

  bool operator == (const Person & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(name == rhs.name))
      return false;
    if (!(age == rhs.age))
      return false;
    if (!(married == rhs.married))
      return false;
    return true;
  }
  bool operator != (const Person &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Person & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Person& obj);

};

void swap(Person &a, Person &b);

} // namespace

#endif
